#!/bin/sh

#
# File:    pc2board
# Purpose: start pc2 client script
# Author:  pc2
# E-mail:  mailto:pc2@ecs.csus.edu
# Revised: Tue Apr 19 20:13:36 PDT 2005
#
# Send e-mail to us if you have questions.. thanks.
#

PC2CN=pc2.board.Board

echo
echo Starting board
echo

echo java -Djava.security.policy=policy.ini $PC2CN $*
java -Djava.security.policy=policy.ini $PC2CN $*

# eof pc2board
