#!/bin/sh
#
# File:    reset.sh 
# Purpose: Completely reset and erase contest data
#
# USE WITH EXTREME CAUTION - will erase ALL contest data
# 
# Revised: Thu Jul 17 20:31:17 PDT 2003
#

java pc2.ZipPC2

rm -fr db OLD *.log

# eof reset.sh
