#!/bin/sh

#
# File:    server
# Purpose: start pc2 sever script
# Author:  pc2
# E-mail:  mailto:pc2@ecs.csus.edu
# Revised: Tue Apr 19 20:13:36 PDT 2005

#
# Send e-mail to us if you have questions.. thanks.
#

PC2CN=pc2.server.Server

echo
echo Starting server
echo

echo java -Djava.security.policy=policy.ini $PC2CN $*
java -Djava.security.policy=policy.ini $PC2CN $*

# eof server
