#!/bin/sh

#
# File:    pc2ver
# Purpose: prints version info for pc2
# Author:  pc2
# E-mail:  mailto:pc2@ecs.csus.edu
# Revised: Tue Jan 25 22:09:17 PST 2005
#
# Send e-mail to us if you have questions.. thanks.
#

java pc2.SystemRevisionInfo

if [ "x$1" == "x-a" ]; then
  java pc2.admin.VersionInfo | grep Version
  java pc2.board.VersionInfo | grep Version
  java pc2.client.VersionInfo | grep Version
  java pc2.ex.VersionInfo | grep Version
  java pc2.judge.VersionInfo | grep Version
  java pc2.judge.aj.VersionInfo | grep Version
  java pc2.server.VersionInfo | grep Version
  java pc2.team.VersionInfo | grep Version
fi

# eof pc2ver
